#!/usr/bin/env bash
#
# macos-defaults
#
# Set reasonable macOS defaults.
#
# Thanks to Mathias Bynens' macOS defaults script:
# - https://github.com/mathiasbynens/dotfiles/blob/master/.macos

PROG=${0##*/}

# macOS only...
if [[ $(uname) != "Darwin" ]]
then
  echo "$PROG script is for macOS only!"
  exit 1
fi

# macOS Sierra only...
if ! [[ $(sw_vers -productVersion) =~ ^10\.11\..+ ]]
then
  echo "$PROG script is intended for macOS versions 10.11.x"
  exit 1
fi

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# General - UI/UX
# ----------------------------------------------------------------------------

# Set hostname. Only the user-friendly name (computer name), the local
# (Bonjour) host name and NetBIOS name get set by the Sharing preference pane.
sudo scutil --set ComputerName demalex
sudo scutil --set LocalHostName demalex
sudo scutil --set HostName demalex
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "demalex"

# Disable open and close window animations (default: not set).
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -boolean false

# Set Sidebar icon size to small.
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -integer 1

# Disable focus ring animation (default: not set).
defaults write NSGlobalDomain NSUseAnimatedFocusRing -boolean false

# Save new documents to disk (not to iCloud) (default: not set).
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -boolean false

# Reduce transparency in macOS.
defaults write com.apple.universalaccess reduceTransparency -boolean true

# Report computer name, macOS version and IP address when clicking the clock
# in the Login window (default: not set).
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Desktop & Screen Saver
# ----------------------------------------------------------------------------

# Disable shadows on screen captures (default: not set).
defaults write com.apple.screencapture disable-shadow -boolean true

# Dashboard
# ----------------------------------------------------------------------------

# Disable Dashboard (default: not set).
defaults write com.apple.dashboard mcx-disabled -boolean true

# Dock
# ----------------------------------------------------------------------------

# Minimize windows using the "Scale" effect.
defaults write com.apple.dock mineffect -string "genie"

# Increase window resize speed for Cocoa applications
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# Minimize windows into their application icon.
defaults write com.apple.dock minimize-to-application -boolean true

# Set the icon size of Dock items to 48 pixels (default: not set).
defaults write com.apple.dock tilesize -integer 23

# Finder
# ----------------------------------------------------------------------------

# New windows show home directory.
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

# Show icons on the desktop for external disks.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -boolean true

# Show icons on the desktop for removable media.
defaults write com.apple.finder ShowRemovableMediaOnDesktop -boolean true

# Show status bar.
defaults write com.apple.finder ShowStatusBar -boolean true

#Always display file extensions in finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

#Display hidden files in finder
defaults write com.apple.finder AppleShowAllFiles true

# Always show scrollbars
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
# Possible values: `WhenScrolling`, `Automatic` and `Always`

# Show path bar.
defaults write com.apple.finder ShowPathbar -bool true

# Finder: allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Safari
# ----------------------------------------------------------------------------

# Disable opening "safe" files automatically after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -boolean false

# Set home page to `about:blank`.
defaults write com.apple.Safari HomePage -string "about:blank"

# Do not automatically update extensions.
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -boolean false

# Show status bar.
defaults write com.apple.Safari ShowStatusBar -boolean true

# Don't show tab bar
defaults write com.apple.Safari AlwaysShowTabBar -bool true

# Don't open "safe" files after downloading
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

# Terminal
# ----------------------------------------------------------------------------

# Add terminal profiles for the Solarized Dark and Solarized Light color
# schemes.
open "../terminal/Solarized Dark.terminal"
sleep 1
open "../terminal/Solarized Light.terminal"
sleep 1

# Make Solarized Light the default terminal profile.
defaults write com.apple.Terminal "Default Window Settings" -string "Solarized Light"
defaults write com.apple.Terminal "Startup Window Settings" -string "Solarized Light"

# Google
# ----------------------------------------------------------------------------

# Use the macOS system-native print preview dialog (default: not set).
defaults write com.google.Chrome DisablePrintPreview -boolean true

# Disable Google Software Update from checking for updates (default: 18000).
defaults write com.google.Keystone.Agent checkInterval 0

# Disable Google Software Update agent.
launchctl unload -w ~/Library/LaunchAgents/com.google.keystone.agent.plist

# Other
# ----------------------------------------------------------------------------

# Use plain text mode for new TextEdit documents
defaults write com.apple.TextEdit RichText -int 0

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Show battery level in percents in menu bar
defaults write com.apple.menuextra.battery ShowPercent -string true

# XCode
# ----------------------------------------------------------------------------
defaults write com.apple.dt.Xcode ShowBuildOperationDuration true

# Show tab bar
defaults write com.apple.dt.Xcode AlwaysShowTabBar -bool true

for app in "Dock" "Terminal" \
  "Finder"; do
	killall "${app}" &> /dev/null
done

echo "Done. Note that some of these changes require a logout/restart to take effect."
